# =============================================================================
# SEÇÃO 1: IMPORTAÇÃO DAS BIBLIOTECAS, PREPARAÇÃO E LIMPEZA DOS DADOS
# =============================================================================
## Carregamento e preparação dos dados
from sklearn.feature_extraction.text import TfidfTransformer, CountVectorizer
from sklearn.linear_model import SGDClassifier
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

import pandas as pd
import re
from nltk.corpus import stopwords
import nltk

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.linear_model import SGDClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

nltk.download('stopwords')
stopwords = stopwords.words('portuguese')

data = pd.read_csv('sample_data/olist_order_reviews_dataset.csv')

#Aqui mantemos somente as colunas que são interessantes para nós
df_model = data[['review_score', 'review_comment_message']].copy()
#E aqui removemos as linhas que não contém comentários escritos nas suas avaliações
df_model.dropna(subset=['review_comment_message'], inplace=True)

#Criamos uma função onde vamos a converter a nota em sentiment

def to_sentiment(score): 
  score = int(score)
  if score <= 2:
    return 'negative'
  elif score >= 4:
    return 'positive'
  else:
    return 'neutral'


#Criaremos a coluna de sentimento com base a sua review score

df_model['sentiment'] = df_model['review_score'].apply(to_sentiment)

#Filtramos fora as avaliações 3 estrelas, que estamos considerando como neutras

df_final = df_model[df_model['sentiment'] != 'neutral'].copy()

print("Preparação dos dados concluída.")
print(f"Total de amostras para o modelo: {len(df_final)}")
print(df_final['sentiment'].value_counts())

# Define as variáveis X (features, o texto) e y (target, o sentimento)
X = df_final.review_comment_message
y = df_final.sentiment

- - - - - - - - - - - - - -  OUTPUT - - - - - - - - - - - - - - 
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
Preparação dos dados concluída.
Total de amostras para o modelo: 37420
sentiment
positive    26530
negative    10890
Name: count, dtype: int64


